version: '3.4'

services:
  gighub:
    container_name: gighub-webapp
    ports:
      - "8000:80"
    image: ${DOCKER_REGISTRY}gighub
    build:
      context: .
      dockerfile: ./GigHub/Dockerfile
    depends_on:
      - db
  db:
    image: "microsoft/mssql-server-linux"
    container_name: "gighub-mssql"
    ports:
        - "1433:1433"
    environment:
        SA_PASSWORD: "Pass@word"
        ACCEPT_EULA: "Y"